/**
 * Canonical definitions for the revenue, retention, and processing-health KPIs.
 *
 * This is deliberately data-only. Query runners and dashboards can consume the
 * same definitions without duplicating event semantics or using legacy funnel
 * events as business truth.
 */

export const CORE_KPI_EVENT_DEFINITIONS = [
  {
    eventName: 'account_created',
    description: 'First successful account setup recorded by the server.',
    owner: 'Growth',
    source: 'app/api/users/setup/route.ts',
    status: 'active',
    requiredProperties: [
      'method',
      'pricingRegion',
      'utmSource',
      'utmMedium',
      'utmCampaign',
      'attributionAvailable',
    ],
    optionalProperties: [],
    kpiRole: 'acquisition_denominator',
  },
  {
    eventName: 'monetization_surface_shown',
    description: 'A unique eligible user can see a purchase CTA on a rendered surface.',
    owner: 'Growth',
    source: 'client monetization surfaces',
    status: 'active',
    requiredProperties: [
      'surface',
      'trigger',
      'offerType',
      'priceId',
      'priceCents',
      'pricingRegion',
      'funnelAttemptId',
    ],
    optionalProperties: ['experimentAssignmentKey'],
    kpiRole: 'ctr_denominator',
  },
  {
    eventName: 'monetization_surface_clicked',
    description: 'A user activates a primary or secondary purchase CTA.',
    owner: 'Growth',
    source: 'client monetization surfaces',
    status: 'active',
    requiredProperties: ['surface', 'trigger', 'cta', 'destination', 'funnelAttemptId'],
    optionalProperties: ['experimentAssignmentKey'],
    kpiRole: 'ctr_numerator',
  },
  {
    eventName: 'plan_selected',
    description: 'A user selects a subscription or credit-pack offer.',
    owner: 'Billing',
    source: 'client checkout entry',
    status: 'active',
    requiredProperties: [
      'purchaseType',
      'planOrPack',
      'priceId',
      'priceCents',
      'pricingRegion',
      'funnelAttemptId',
    ],
    optionalProperties: [],
    kpiRole: 'offer_selection',
  },
  {
    eventName: 'checkout_opened',
    description: 'Stripe checkout is requested for a selected offer.',
    owner: 'Billing',
    source: 'client checkout flow',
    status: 'active',
    requiredProperties: [
      'purchaseType',
      'priceId',
      'entrySurface',
      'trigger',
      'funnelAttemptId',
      'uiMode',
    ],
    optionalProperties: [],
    kpiRole: 'checkout_start',
  },
  {
    eventName: 'checkout_error',
    description: 'Checkout cannot load, continue, or complete on the client path.',
    owner: 'Billing',
    source: 'client checkout flow',
    status: 'active',
    requiredProperties: [
      'errorType',
      'failurePoint',
      'priceId',
      'uiMode',
      'funnelAttemptId',
      'retryable',
    ],
    optionalProperties: [],
    kpiRole: 'checkout_friction',
  },
  {
    eventName: 'image_upscaled',
    description: 'A user receives a successfully processed image result.',
    owner: 'Platform',
    source: 'app/api/upscale/route.ts and client processors',
    status: 'active',
    requiredProperties: [
      'qualityTier',
      'scaleFactor',
      'inputWidth',
      'inputHeight',
      'outputWidth',
      'outputHeight',
      'fileType',
      'fileSizeBucket',
      'durationMs',
    ],
    optionalProperties: [],
    kpiRole: 'activation_usage',
  },
  {
    eventName: 'processing_failed',
    description: 'A processing attempt ends without a delivered result.',
    owner: 'Platform',
    source: 'app/api/upscale/route.ts',
    status: 'active',
    requiredProperties: [
      'errorType',
      'reason',
      'provider',
      'qualityTier',
      'retryable',
      'durationMs',
      'requestId',
    ],
    optionalProperties: [],
    kpiRole: 'processing_health',
  },
  {
    eventName: 'checkout_completed',
    description: 'Stripe Checkout reports a completed session; payment may remain pending.',
    owner: 'Billing',
    source: 'Stripe checkout webhook',
    status: 'active',
    requiredProperties: [
      'purchaseType',
      'sessionId',
      'amountCents',
      'currency',
      'paymentStatus',
      'pricingRegion',
    ],
    optionalProperties: [],
    kpiRole: 'checkout_funnel_only',
  },
  {
    eventName: 'purchase_confirmed',
    description: 'A successful initial charge is confirmed by a server-side Stripe handler.',
    owner: 'Billing',
    source: 'Stripe payment/invoice webhook',
    status: 'active',
    requiredProperties: ['purchaseType', 'amountCents', 'currency', 'priceId'],
    optionalProperties: ['stripeCheckoutSessionId', 'invoiceId', 'sourceObjectId'],
    kpiRole: 'purchase_conversion',
  },
  {
    eventName: 'revenue_received',
    description: 'A successful initial or recurring charge represented in Amplitude Revenue.',
    owner: 'Billing',
    source: 'Stripe payment/invoice webhook',
    status: 'active',
    requiredProperties: [
      '$revenue',
      '$productId',
      '$quantity',
      '$revenueType',
      'amountCents',
      'currency',
      'sourceObjectId',
    ],
    optionalProperties: [],
    kpiRole: 'recognized_revenue',
  },
  {
    eventName: 'subscription_created',
    description: 'A Stripe subscription reaches an accepted active or trialing state.',
    owner: 'Billing',
    source: 'customer.subscription.created/updated webhook',
    status: 'active',
    requiredProperties: [
      'plan',
      'amountCents',
      'currency',
      'billingInterval',
      'status',
      'subscriptionId',
    ],
    optionalProperties: [],
    kpiRole: 'new_subscriptions',
  },
  {
    eventName: 'subscription_renewed',
    description: 'A paid subscription-cycle invoice is recognized.',
    owner: 'Billing',
    source: 'invoice.payment_succeeded webhook',
    status: 'active',
    requiredProperties: [
      'plan',
      'amountCents',
      'currency',
      'subscriptionId',
      'invoiceId',
      'creditsAdded',
    ],
    optionalProperties: [],
    kpiRole: 'renewal_health',
  },
  {
    eventName: 'subscription_cancel_scheduled',
    description: 'Cancellation is scheduled for the end of the current period.',
    owner: 'Retention',
    source: 'customer.subscription.updated webhook',
    status: 'active',
    requiredProperties: ['plan', 'subscriptionId', 'effectiveAt', 'reasonCategory', 'reasonSource'],
    optionalProperties: [],
    kpiRole: 'gross_churn_intent',
  },
  {
    eventName: 'subscription_cancel_reversed',
    description: 'A scheduled cancellation is reversed before termination.',
    owner: 'Retention',
    source: 'customer.subscription.updated webhook',
    status: 'active',
    requiredProperties: ['plan', 'subscriptionId', 'reversedAt'],
    optionalProperties: [],
    kpiRole: 'cancellation_recovery',
  },
  {
    eventName: 'subscription_canceled',
    description: 'Stripe reports that subscription access has ended.',
    owner: 'Retention',
    source: 'customer.subscription.deleted webhook',
    status: 'active',
    requiredProperties: ['plan', 'subscriptionId', 'effectiveAt', 'reasonCategory', 'reasonSource'],
    optionalProperties: [],
    kpiRole: 'effective_logo_churn',
  },
  {
    eventName: 'payment_failed',
    description: 'Stripe confirms a failed one-time charge or invoice payment.',
    owner: 'Billing',
    source: 'Stripe payment/invoice webhook',
    status: 'active',
    requiredProperties: ['errorType', 'attemptCount', 'customerId', 'sourceObjectId'],
    optionalProperties: [],
    kpiRole: 'payment_health',
  },
  {
    eventName: 'payment_recovery_started',
    description: 'An eligible user opens a recovery path for a failed payment.',
    owner: 'Recovery',
    source: 'recovery client flow',
    status: 'active',
    requiredProperties: ['purchaseType', 'failureType', 'recoveryChannel', 'funnelAttemptId'],
    optionalProperties: [],
    kpiRole: 'payment_recovery_funnel',
  },
  {
    eventName: 'payment_recovered',
    description: 'A previously failed payment later succeeds.',
    owner: 'Recovery',
    source: 'Stripe payment/invoice webhook',
    status: 'active',
    requiredProperties: [
      'purchaseType',
      'amountCents',
      'currency',
      'sourceObjectId',
      'originalFailureObjectId',
      'recoveryChannel',
    ],
    optionalProperties: [],
    kpiRole: 'recovered_revenue',
  },
] as const;

export type TCoreKpiEventName = (typeof CORE_KPI_EVENT_DEFINITIONS)[number]['eventName'];

export const CORE_KPI_EVENT_NAMES: readonly TCoreKpiEventName[] = CORE_KPI_EVENT_DEFINITIONS.map(
  definition => definition.eventName
);

export const CORE_KPI_RELEASE_ANNOTATION = {
  releaseDate: '2026-08-01',
  preReleaseInterval: 'All data before the corrected telemetry release is annotated as unreliable.',
} as const;

export function getCoreKpiDefinition(
  eventName: string
): (typeof CORE_KPI_EVENT_DEFINITIONS)[number] | undefined {
  return CORE_KPI_EVENT_DEFINITIONS.find(definition => definition.eventName === eventName);
}
