/**
 * QA: Data Loader Interactive Tools Tests
 * Validates that getAllInteractiveTools, getInteractiveToolData, getAllToolSlugs
 * work correctly with the expanded interactive-tools.json
 * Generated by Night Watch QA agent for PR #13
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// We need to test the actual data-loader logic against the real JSON data.
// Since data-loader uses React cache(), we test via dynamic import.

describe('QA: Data Loader - Interactive Tools', () => {
  beforeEach(() => {
    vi.resetModules();
  });

  it('getAllInteractiveTools should return all interactive tool pages', async () => {
    const { getAllInteractiveTools } = await import('@/lib/seo/data-loader');
    const tools = await getAllInteractiveTools();

    expect(tools).toBeInstanceOf(Array);
    expect(tools.length).toBeGreaterThanOrEqual(20);

    // All should have category 'tools'
    for (const tool of tools) {
      expect(tool.category).toBe('tools');
    }
  });

  it('getInteractiveToolData should return data for a known slug', async () => {
    const { getInteractiveToolData } = await import('@/lib/seo/data-loader');

    const tool = await getInteractiveToolData('image-to-text');
    expect(tool).not.toBeNull();
    expect(tool!.slug).toBe('image-to-text');
    expect(tool!.toolComponent).toBe('ImageToText');
    expect(tool!.isInteractive).toBe(true);
  });

  it('getInteractiveToolData should return null for unknown slug', async () => {
    const { getInteractiveToolData } = await import('@/lib/seo/data-loader');

    const tool = await getInteractiveToolData('non-existent-tool-xyz');
    expect(tool).toBeNull();
  });

  it('getToolData should find interactive tools not in DEDICATED_ROUTE_SLUGS', async () => {
    const { getToolData } = await import('@/lib/seo/data-loader');

    // These are new interactive tools that should be found via getToolData
    const newSlugs = [
      'heic-to-jpg',
      'pdf-to-jpg',
      'image-to-pdf',
      'background-changer',
      'image-to-text',
      'ocr-online',
    ];

    for (const slug of newSlugs) {
      const tool = await getToolData(slug);
      expect(tool).not.toBeNull();
      expect(tool!.slug).toBe(slug);
    }
  });

  it('getAllToolSlugs should include non-dedicated interactive tool slugs', async () => {
    const { getAllToolSlugs } = await import('@/lib/seo/data-loader');
    const slugs = await getAllToolSlugs();

    // These new tools should be in the slug list (they are NOT in DEDICATED_ROUTE_SLUGS)
    expect(slugs).toContain('heic-to-jpg');
    expect(slugs).toContain('heic-to-png');
    expect(slugs).toContain('pdf-to-jpg');
    expect(slugs).toContain('pdf-to-png');
    expect(slugs).toContain('image-to-pdf');
    expect(slugs).toContain('jpg-to-pdf');
    expect(slugs).toContain('background-changer');
    expect(slugs).toContain('image-to-text');
    expect(slugs).toContain('ocr-online');
    expect(slugs).toContain('bmp-to-jpg');
    expect(slugs).toContain('gif-to-jpg');
    expect(slugs).toContain('svg-to-jpg');
    expect(slugs).toContain('avif-to-jpg');
    expect(slugs).toContain('make-image-transparent');
  });

  it('getAllToolSlugs should NOT include dedicated-route interactive tool slugs', async () => {
    const { getAllToolSlugs } = await import('@/lib/seo/data-loader');
    const slugs = await getAllToolSlugs();

    // These have dedicated sub-routes and should be filtered out
    const dedicatedSlugs = [
      'image-resizer',
      'image-compressor',
      'png-to-jpg',
      'jpg-to-png',
      'webp-to-jpg',
      'webp-to-png',
      'jpg-to-webp',
      'png-to-webp',
    ];

    for (const slug of dedicatedSlugs) {
      expect(slugs).not.toContain(slug);
    }
  });

  it('getAllToolSlugs should have no duplicates', async () => {
    const { getAllToolSlugs } = await import('@/lib/seo/data-loader');
    const slugs = await getAllToolSlugs();

    const uniqueSlugs = new Set(slugs);
    expect(uniqueSlugs.size).toBe(slugs.length);
  });
});
