/**
 * QA: Interactive Tools Data Integrity Tests
 * Validates interactive-tools.json structure, SEO fields, and tool component mappings
 * Generated by Night Watch QA agent for PR #13
 */

import { describe, it, expect } from 'vitest';
import interactiveToolsData from '@/app/seo/data/interactive-tools.json';

const VALID_TOOL_COMPONENTS = [
  'ImageResizer',
  'ImageCompressor',
  'FormatConverter',
  'BulkImageCompressor',
  'BulkImageResizer',
  'BackgroundRemover',
  'BackgroundChanger',
  'HeicConverter',
  'PdfToImageConverter',
  'ImageToPdfConverter',
  'ImageToText',
  'ExifRemover',
  'ImageCropper',
  'BrowserImageUpscaler',
];

const pages = interactiveToolsData.pages;

describe('QA: Interactive Tools Data Integrity', () => {
  it('should have the correct category', () => {
    expect(interactiveToolsData.category).toBe('tools');
  });

  it('should have at least 20 pages (expanded set)', () => {
    expect(pages.length).toBeGreaterThanOrEqual(20);
  });

  it('should have no duplicate slugs', () => {
    const slugs = pages.map(p => p.slug);
    const uniqueSlugs = new Set(slugs);
    expect(uniqueSlugs.size).toBe(slugs.length);
  });

  describe('each page should have required base fields', () => {
    for (const page of pages) {
      it(`"${page.slug}" should have all required pSEO fields`, () => {
        expect(page.slug).toBeTruthy();
        expect(page.title).toBeTruthy();
        expect(page.metaTitle).toBeTruthy();
        expect(page.metaDescription).toBeTruthy();
        expect(page.h1).toBeTruthy();
        expect(page.intro).toBeTruthy();
        expect(page.primaryKeyword).toBeTruthy();
        expect(page.secondaryKeywords).toBeInstanceOf(Array);
        expect(page.secondaryKeywords.length).toBeGreaterThan(0);
        expect(page.lastUpdated).toBeTruthy();
        expect(page.category).toBe('tools');
        expect(page.toolName).toBeTruthy();
        expect(page.description).toBeTruthy();
      });
    }
  });

  describe('SEO field constraints', () => {
    for (const page of pages) {
      it(`"${page.slug}" metaTitle should be <= 70 chars`, () => {
        expect(page.metaTitle.length).toBeLessThanOrEqual(70);
      });

      it(`"${page.slug}" metaDescription should be <= 160 chars`, () => {
        expect(page.metaDescription.length).toBeLessThanOrEqual(160);
      });
    }
  });

  describe('interactive tool configuration', () => {
    const interactivePages = pages.filter(p => p.isInteractive);

    it('should have at least 15 interactive pages', () => {
      expect(interactivePages.length).toBeGreaterThanOrEqual(15);
    });

    for (const page of interactivePages) {
      it(`"${page.slug}" should have a valid toolComponent`, () => {
        expect(page.toolComponent).toBeTruthy();
        expect(VALID_TOOL_COMPONENTS).toContain(page.toolComponent);
      });
    }
  });

  describe('content sections', () => {
    for (const page of pages) {
      it(`"${page.slug}" should have features array`, () => {
        expect(page.features).toBeInstanceOf(Array);
        expect(page.features.length).toBeGreaterThan(0);
        for (const feature of page.features) {
          expect(feature.title).toBeTruthy();
          expect(feature.description).toBeTruthy();
        }
      });

      it(`"${page.slug}" should have useCases array`, () => {
        expect(page.useCases).toBeInstanceOf(Array);
        expect(page.useCases.length).toBeGreaterThan(0);
      });

      it(`"${page.slug}" should have benefits array`, () => {
        expect(page.benefits).toBeInstanceOf(Array);
        expect(page.benefits.length).toBeGreaterThan(0);
      });

      it(`"${page.slug}" should have howItWorks array`, () => {
        expect(page.howItWorks).toBeInstanceOf(Array);
        expect(page.howItWorks.length).toBeGreaterThan(0);
      });

      it(`"${page.slug}" should have faq array`, () => {
        expect(page.faq).toBeInstanceOf(Array);
        expect(page.faq.length).toBeGreaterThan(0);
        for (const faq of page.faq) {
          expect(faq.question).toBeTruthy();
          expect(faq.answer).toBeTruthy();
        }
      });

      it(`"${page.slug}" should have ctaText and ctaUrl`, () => {
        expect(page.ctaText).toBeTruthy();
        expect(page.ctaUrl).toBeTruthy();
      });
    }
  });

  describe('relatedTools references', () => {
    const allSlugs = new Set(pages.map(p => p.slug));

    for (const page of pages) {
      if (page.relatedTools && page.relatedTools.length > 0) {
        it(`"${page.slug}" relatedTools should not include self`, () => {
          expect(page.relatedTools).not.toContain(page.slug);
        });
      }
    }
  });

  describe('new tools added in PR #13', () => {
    const newToolSlugs = [
      'bmp-to-jpg',
      'gif-to-jpg',
      'svg-to-jpg',
      'avif-to-jpg',
      'heic-to-jpg',
      'heic-to-png',
      'pdf-to-jpg',
      'pdf-to-png',
      'image-to-pdf',
      'jpg-to-pdf',
      'background-changer',
      'image-to-text',
      'ocr-online',
    ];

    for (const slug of newToolSlugs) {
      it(`new tool "${slug}" should exist in interactive-tools.json`, () => {
        const page = pages.find(p => p.slug === slug);
        expect(page).toBeDefined();
      });
    }

    it('heic-to-jpg should use HeicConverter component', () => {
      const page = pages.find(p => p.slug === 'heic-to-jpg');
      expect(page?.toolComponent).toBe('HeicConverter');
    });

    it('heic-to-png should use HeicConverter component', () => {
      const page = pages.find(p => p.slug === 'heic-to-png');
      expect(page?.toolComponent).toBe('HeicConverter');
    });

    it('pdf-to-jpg should use PdfToImageConverter component', () => {
      const page = pages.find(p => p.slug === 'pdf-to-jpg');
      expect(page?.toolComponent).toBe('PdfToImageConverter');
    });

    it('image-to-pdf should use ImageToPdfConverter component', () => {
      const page = pages.find(p => p.slug === 'image-to-pdf');
      expect(page?.toolComponent).toBe('ImageToPdfConverter');
    });

    it('background-changer should use BackgroundChanger component', () => {
      const page = pages.find(p => p.slug === 'background-changer');
      expect(page?.toolComponent).toBe('BackgroundChanger');
    });

    it('image-to-text should use ImageToText component', () => {
      const page = pages.find(p => p.slug === 'image-to-text');
      expect(page?.toolComponent).toBe('ImageToText');
    });

    it('ocr-online should use ImageToText component', () => {
      const page = pages.find(p => p.slug === 'ocr-online');
      expect(page?.toolComponent).toBe('ImageToText');
    });
  });
});
