/**
 * QA: Related Pages - Tools Category Tests
 * Validates that the updated related-pages logic correctly resolves
 * relatedTools from interactive-tools.json data
 * Generated by Night Watch QA agent for PR #13
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { getRelatedPages } from '@/lib/seo/related-pages';

// Mock all data-loader functions
vi.mock('@/lib/seo/data-loader', () => ({
  getAllPlatforms: vi.fn(() => Promise.resolve([])),
  getAllFormats: vi.fn(() => Promise.resolve([])),
  getAllFormatScale: vi.fn(() => Promise.resolve([])),
  getAllPlatformFormat: vi.fn(() => Promise.resolve([])),
  getAllDeviceUse: vi.fn(() => Promise.resolve([])),
  getAllTools: vi.fn(() =>
    Promise.resolve([
      {
        slug: 'ai-image-upscaler',
        toolName: 'AI Image Upscaler',
        description: 'Upscale images with AI',
        category: 'tools',
      },
      {
        slug: 'ai-photo-enhancer',
        toolName: 'AI Photo Enhancer',
        description: 'Enhance photos with AI',
        category: 'tools',
      },
    ])
  ),
  getAllInteractiveTools: vi.fn(() =>
    Promise.resolve([
      {
        slug: 'image-to-text',
        toolName: 'Image to Text (OCR)',
        description: 'Extract text from images',
        category: 'tools',
        isInteractive: true,
        relatedTools: ['ocr-online', 'pdf-to-jpg'],
      },
      {
        slug: 'ocr-online',
        toolName: 'OCR Online',
        description: 'Free online OCR tool',
        category: 'tools',
        isInteractive: true,
        relatedTools: ['image-to-text', 'pdf-to-png'],
      },
      {
        slug: 'pdf-to-jpg',
        toolName: 'PDF to JPG Converter',
        description: 'Convert PDF to JPG',
        category: 'tools',
        isInteractive: true,
        relatedTools: ['pdf-to-png', 'image-to-pdf'],
      },
      {
        slug: 'pdf-to-png',
        toolName: 'PDF to PNG Converter',
        description: 'Convert PDF to PNG',
        category: 'tools',
        isInteractive: true,
        relatedTools: ['pdf-to-jpg', 'image-to-pdf'],
      },
      {
        slug: 'image-to-pdf',
        toolName: 'Image to PDF Converter',
        description: 'Convert images to PDF',
        category: 'tools',
        isInteractive: true,
        relatedTools: ['jpg-to-pdf', 'pdf-to-jpg'],
      },
      {
        slug: 'background-changer',
        toolName: 'Background Changer',
        description: 'Change image backgrounds',
        category: 'tools',
        isInteractive: true,
        relatedTools: ['make-image-transparent'],
      },
    ])
  ),
  getInteractiveToolData: vi.fn((slug: string) => {
    const tools: Record<string, any> = {
      'image-to-text': {
        slug: 'image-to-text',
        relatedTools: ['ocr-online', 'pdf-to-jpg'],
      },
      'ocr-online': {
        slug: 'ocr-online',
        relatedTools: ['image-to-text', 'pdf-to-png'],
      },
      'background-changer': {
        slug: 'background-changer',
        relatedTools: ['make-image-transparent'],
      },
    };
    return Promise.resolve(tools[slug] || null);
  }),
  getAllContentPages: vi.fn(() => Promise.resolve([])),
  getAllCameraRawPages: vi.fn(() => Promise.resolve([])),
  getAllBulkToolsPages: vi.fn(() => Promise.resolve([])),
  getAllDeviceOptimizationPages: vi.fn(() => Promise.resolve([])),
  getAllIndustryInsightsPages: vi.fn(() => Promise.resolve([])),
  getAllPhotoRestorationPages: vi.fn(() => Promise.resolve([])),
}));

describe('QA: Related Pages - Tools Category', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should resolve relatedTools from interactive tool data', async () => {
    const pages = await getRelatedPages('tools', 'image-to-text', 'en');

    expect(pages).toBeDefined();
    expect(Array.isArray(pages)).toBe(true);
    expect(pages.length).toBeGreaterThan(0);

    // Should include ocr-online from relatedTools
    const ocrPage = pages.find(p => p.slug === 'ocr-online');
    expect(ocrPage).toBeDefined();
    expect(ocrPage!.url).toBe('/tools/ocr-online');
  });

  it('should not include the current page in results', async () => {
    const pages = await getRelatedPages('tools', 'image-to-text', 'en');

    const selfPage = pages.find(p => p.slug === 'image-to-text');
    expect(selfPage).toBeUndefined();
  });

  it('should fill remaining slots from other interactive tools', async () => {
    const pages = await getRelatedPages('tools', 'background-changer', 'en');

    expect(pages).toBeDefined();
    expect(pages.length).toBeGreaterThanOrEqual(4);
  });

  it('should not exceed 6 related pages', async () => {
    const pages = await getRelatedPages('tools', 'image-to-text', 'en');

    expect(pages.length).toBeLessThanOrEqual(6);
  });

  it('should handle tool with no relatedTools gracefully', async () => {
    const pages = await getRelatedPages('tools', 'unknown-tool', 'en');

    expect(pages).toBeDefined();
    expect(Array.isArray(pages)).toBe(true);
    // Should still return some pages from the fallback (other interactive tools)
    expect(pages.length).toBeGreaterThan(0);
  });

  it('should include locale prefix for non-English locale', async () => {
    const pages = await getRelatedPages('tools', 'ocr-online', 'es');

    if (pages.length > 0) {
      expect(pages[0].locale).toBe('es');
      expect(pages[0].url).toContain('/es/');
    }
  });

  it('should not include locale prefix for English', async () => {
    const pages = await getRelatedPages('tools', 'ocr-online', 'en');

    if (pages.length > 0) {
      expect(pages[0].url).not.toContain('/en/');
      expect(pages[0].url).toMatch(/^\/tools\//);
    }
  });
});
