/**
 * QA: Tools Hub Page Category Grouping Tests
 * Validates the CATEGORY_GROUPS mapping and data aggregation on the tools hub page
 * Generated by Night Watch QA agent for PR #13
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// The CATEGORY_GROUPS definition from the tools hub page
const CATEGORY_GROUPS = [
  {
    label: 'AI Image Tools',
    slugs: [
      'ai-image-upscaler',
      'ai-photo-enhancer',
      'photo-quality-enhancer',
      'ai-background-remover',
      'remove-bg',
      'transparent-background-maker',
      'make-image-transparent',
      'image-cutout-tool',
      'smart-ai-enhancement',
    ],
  },
  {
    label: 'Format Converters',
    slugs: ['bmp-to-jpg', 'gif-to-jpg', 'svg-to-jpg', 'avif-to-jpg', 'heic-to-jpg', 'heic-to-png'],
  },
  {
    label: 'PDF Tools',
    slugs: ['pdf-to-jpg', 'pdf-to-png', 'image-to-pdf', 'jpg-to-pdf'],
  },
  {
    label: 'Image Editing',
    slugs: ['background-changer', 'image-to-text', 'ocr-online'],
  },
];

describe('QA: Tools Hub Page Category Groups', () => {
  it('should have 4 category groups defined', () => {
    expect(CATEGORY_GROUPS.length).toBe(4);
  });

  it('should have no duplicate slugs across groups', () => {
    const allSlugs = CATEGORY_GROUPS.flatMap(g => g.slugs);
    const uniqueSlugs = new Set(allSlugs);
    expect(uniqueSlugs.size).toBe(allSlugs.length);
  });

  it('Format Converters group should contain new converter tools', () => {
    const formatGroup = CATEGORY_GROUPS.find(g => g.label === 'Format Converters');
    expect(formatGroup).toBeDefined();
    expect(formatGroup!.slugs).toContain('bmp-to-jpg');
    expect(formatGroup!.slugs).toContain('gif-to-jpg');
    expect(formatGroup!.slugs).toContain('svg-to-jpg');
    expect(formatGroup!.slugs).toContain('avif-to-jpg');
    expect(formatGroup!.slugs).toContain('heic-to-jpg');
    expect(formatGroup!.slugs).toContain('heic-to-png');
  });

  it('PDF Tools group should contain PDF conversion tools', () => {
    const pdfGroup = CATEGORY_GROUPS.find(g => g.label === 'PDF Tools');
    expect(pdfGroup).toBeDefined();
    expect(pdfGroup!.slugs).toContain('pdf-to-jpg');
    expect(pdfGroup!.slugs).toContain('pdf-to-png');
    expect(pdfGroup!.slugs).toContain('image-to-pdf');
    expect(pdfGroup!.slugs).toContain('jpg-to-pdf');
  });

  it('Image Editing group should contain new editing tools', () => {
    const editingGroup = CATEGORY_GROUPS.find(g => g.label === 'Image Editing');
    expect(editingGroup).toBeDefined();
    expect(editingGroup!.slugs).toContain('background-changer');
    expect(editingGroup!.slugs).toContain('image-to-text');
    expect(editingGroup!.slugs).toContain('ocr-online');
  });

  describe('all grouped slugs should exist in data', () => {
    // Load real data to check that grouped slugs actually exist
    it('should find all grouped slugs in combined tool data', async () => {
      const { getAllTools, getAllInteractiveTools } = await import('@/lib/seo/data-loader');
      const [staticTools, interactiveTools] = await Promise.all([
        getAllTools(),
        getAllInteractiveTools(),
      ]);
      const allToolSlugs = new Set([...staticTools, ...interactiveTools].map(t => t.slug));

      const groupedSlugs = CATEGORY_GROUPS.flatMap(g => g.slugs);
      const missingSlugs: string[] = [];

      for (const slug of groupedSlugs) {
        if (!allToolSlugs.has(slug)) {
          missingSlugs.push(slug);
        }
      }

      // Report which slugs are missing (if any)
      if (missingSlugs.length > 0) {
        console.warn('Missing slugs in tool data:', missingSlugs);
      }
      // Allow some slugs to be from static tools data (not just interactive-tools.json)
      // The hub page loads both sources, so all grouped slugs should be findable
      expect(missingSlugs.length).toBe(0);
    });
  });
});

describe('QA: Tools Hub - Data Aggregation', () => {
  it('getAllTools + getAllInteractiveTools should cover all hub page tools', async () => {
    const { getAllTools, getAllInteractiveTools } = await import('@/lib/seo/data-loader');
    const [staticTools, interactiveTools] = await Promise.all([
      getAllTools(),
      getAllInteractiveTools(),
    ]);

    const combined = [...staticTools, ...interactiveTools];
    expect(combined.length).toBeGreaterThan(0);

    // Each tool should have at minimum: slug, title, description
    for (const tool of combined) {
      expect(tool.slug).toBeTruthy();
      expect(tool.title || tool.toolName).toBeTruthy();
      expect(tool.description).toBeTruthy();
    }
  });

  it('interactive tools should have isInteractive flag or toolComponent', async () => {
    const { getAllInteractiveTools } = await import('@/lib/seo/data-loader');
    const interactiveTools = await getAllInteractiveTools();

    // All interactive tools should be identifiable as interactive
    const withComponent = interactiveTools.filter(t => t.toolComponent);
    expect(withComponent.length).toBeGreaterThanOrEqual(15);
  });
});
