/**
 * Regional Dynamic Pricing Configuration
 *
 * Maps countries to pricing regions with discount percentages.
 * Both subscriptions and credit packs use Stripe price_data (inline amounts)
 * at checkout — no regional Stripe Price objects needed.
 *
 * Abuse model:
 * - CF-IPCountry is Cloudflare-edge-set, not spoofable by client
 * - VPN users get the VPN exit node's country (acceptable tradeoff)
 * - Fingerprint system already catches multi-account fraud
 */

import { serverEnv } from './env';

export type PricingRegion =
  | 'standard'
  | 'south_asia'
  | 'southeast_asia'
  | 'latam'
  | 'eastern_europe'
  | 'africa';

export interface IPricingRegionConfig {
  region: PricingRegion;
  discountPercent: number;
  countries: readonly string[];
}

const PRICING_REGION_CONFIGS: readonly IPricingRegionConfig[] = [
  {
    region: 'south_asia',
    discountPercent: 65,
    countries: ['IN', 'PK', 'BD', 'LK', 'NP', 'AF', 'BT'],
  },
  {
    region: 'southeast_asia',
    discountPercent: 60,
    countries: ['PH', 'ID', 'VN', 'TH', 'MM', 'KH', 'LA', 'MY', 'TL'],
  },
  {
    region: 'latam',
    discountPercent: 50,
    // South America + Central America + Caribbean
    countries: [
      'BR',
      'MX',
      'CO',
      'AR',
      'PE',
      'CL',
      'EC',
      'VE',
      'BO',
      'PY',
      'UY',
      'GY',
      'SR',
      'GT',
      'HN',
      'SV',
      'NI',
      'CR',
      'PA',
      'BZ',
      'DO',
      'HT',
      'JM',
      'CU',
      'TT',
    ],
  },
  {
    region: 'eastern_europe',
    discountPercent: 40,
    // Balkans + former Soviet + Turkey + Central Asia
    countries: [
      'UA',
      'RO',
      'BG',
      'RS',
      'HR',
      'BA',
      'MK',
      'AL',
      'MD',
      'GE',
      'ME',
      'XK',
      'RU',
      'BY',
      'AM',
      'AZ',
      'KZ',
      'UZ',
      'KG',
      'TJ',
      'TM',
      'TR',
      'CN',
      'IR',
      'IQ',
      'JO',
      'LB',
    ],
  },
  {
    region: 'africa',
    discountPercent: 65,
    countries: [
      // North Africa
      'EG',
      'MA',
      'TN',
      'DZ',
      'LY',
      'SD',
      // West Africa
      'NG',
      'GH',
      'SN',
      'CI',
      'ML',
      'BF',
      'NE',
      'TD',
      'GN',
      'SL',
      'LR',
      'TG',
      'BJ',
      'MR',
      'GM',
      'GW',
      'CV',
      'ST',
      // Central Africa
      'CM',
      'CD',
      'CF',
      'CG',
      'GA',
      'GQ',
      'AO',
      // East Africa
      'ET',
      'KE',
      'TZ',
      'UG',
      'RW',
      'BI',
      'MZ',
      'MG',
      'DJ',
      'ER',
      'SO',
      'SS',
      'KM',
      // Southern Africa
      'ZA',
      'ZM',
      'ZW',
      'MW',
      'BW',
      'NA',
      'LS',
      'SZ',
    ],
  },
] as const;

const STANDARD_CONFIG: IPricingRegionConfig = {
  region: 'standard',
  discountPercent: 0,
  countries: [],
};

// Build a country-to-config lookup map for O(1) access
const countryToRegionMap = new Map<string, IPricingRegionConfig>();
for (const config of PRICING_REGION_CONFIGS) {
  for (const country of config.countries) {
    countryToRegionMap.set(country, config);
  }
}

/**
 * Get the pricing region config for a country code.
 * Returns standard (0% discount) for unknown/unmapped countries.
 */
export function getPricingRegion(countryCode: string): IPricingRegionConfig {
  if (!countryCode) return STANDARD_CONFIG;
  return countryToRegionMap.get(countryCode.toUpperCase()) ?? STANDARD_CONFIG;
}

/**
 * Get just the discount percentage for a country code.
 */
export function getDiscountPercent(countryCode: string): number {
  return getPricingRegion(countryCode).discountPercent;
}

/**
 * Calculate the discounted price in cents, rounded to nearest cent.
 */
export function getDiscountedPriceInCents(
  basePriceInCents: number,
  discountPercent: number
): number {
  if (discountPercent <= 0) return basePriceInCents;
  return Math.round(basePriceInCents * (1 - discountPercent / 100));
}

/**
 * Maps plan keys (as stored in subscription metadata) to their base Stripe Price env var.
 * Used by webhook handlers to resolve the base price ID when a subscription was created
 * with price_data (Stripe auto-generates a throwaway price ID in that case).
 */
const PLAN_KEY_TO_BASE_ENV: Record<string, string> = {
  starter: 'STRIPE_PRICE_STARTER',
  hobby: 'STRIPE_PRICE_HOBBY',
  pro: 'STRIPE_PRICE_PRO',
  business: 'STRIPE_PRICE_BUSINESS',
};

/**
 * Given a plan key (e.g. 'starter'), return the base Stripe Price ID from env.
 * Webhook handlers use this as a fallback when the subscription's price ID was
 * auto-generated by Stripe (happens when the session used price_data).
 */
export function getBasePriceIdByPlanKey(planKey: string): string | null {
  const envKey = PLAN_KEY_TO_BASE_ENV[planKey];
  if (!envKey) return null;
  const priceId = serverEnv[envKey as keyof typeof serverEnv] as string | undefined;
  return priceId && priceId.startsWith('price_') ? priceId : null;
}

export { PRICING_REGION_CONFIGS };
