/**
 * Centralized Stripe Payment Configuration
 *
 * This file contains all Stripe pricing and product configuration.
 * Now derives from subscription.config.ts to ensure consistency.
 *
 * Legacy: Auto-generated by stripe-setup.sh on Fri Dec  5 17:19:50 PST 2025
 * Updated: Unified with subscription.config.ts as the single source of truth
 */

import { clientEnv, serverEnv } from './env';
import {
  getPriceIndex,
  resolvePriceId,
  resolvePlanOrPack,
  assertKnownPriceId,
  buildStripePrices,
  buildSubscriptionPlans,
  buildCreditPacks,
  buildHomepageTiers
} from './subscription.utils';

/**
 * Stripe subscription plan metadata interface
 */
export interface ISubscriptionPlanMetadata {
  name: string;
  creditsPerMonth: number;
  maxRollover: number;
}

// Stripe Price IDs - Derived from subscription.config.ts (single source of truth)
export const STRIPE_PRICES = buildStripePrices() as {
  // Subscription plans
  HOBBY_MONTHLY: string;
  PRO_MONTHLY: string;
  BUSINESS_MONTHLY: string;
  // Credit packs
  SMALL_CREDITS: string;
  MEDIUM_CREDITS: string;
  LARGE_CREDITS: string;
};

export type StripePriceKey = keyof typeof STRIPE_PRICES;

/**
 * Credit pack configuration with associated credits
 * Derived from subscription.config.ts
 */
export const CREDIT_PACKS = buildCreditPacks() as {
  SMALL_CREDITS: {
    name: string;
    description: string;
    price: number;
    credits: number;
    features: readonly string[];
    popular?: boolean;
  };
  MEDIUM_CREDITS: {
    name: string;
    description: string;
    price: number;
    credits: number;
    features: readonly string[];
    popular?: boolean;
  };
  LARGE_CREDITS: {
    name: string;
    description: string;
    price: number;
    credits: number;
    features: readonly string[];
    popular?: boolean;
  };
};

/**
 * Subscription plan configuration
 * Derived from subscription.config.ts
 */
export const SUBSCRIPTION_PLANS = buildSubscriptionPlans() as {
  HOBBY_MONTHLY: {
    name: string;
    description: string;
    price: number;
    interval: 'month' | 'year';
    creditsPerMonth: number;
    maxRollover: number;
    key: string;
    features: readonly string[];
    recommended?: boolean;
  };
  PRO_MONTHLY: {
    name: string;
    description: string;
    price: number;
    interval: 'month' | 'year';
    creditsPerMonth: number;
    maxRollover: number;
    key: string;
    features: readonly string[];
    recommended?: boolean;
  };
  BUSINESS_MONTHLY: {
    name: string;
    description: string;
    price: number;
    interval: 'month' | 'year';
    creditsPerMonth: number;
    maxRollover: number;
    key: string;
    features: readonly string[];
    recommended?: boolean;
  };
};

/**
 * Check if Stripe prices are configured
 */
export function isStripePricesConfigured(): boolean {
  return true; // Always return true for static configuration
}

/**
 * Get the price ID for a given key, with validation
 */
export function getPriceId(key: StripePriceKey): string {
  const priceId = STRIPE_PRICES[key];
  if (!priceId || priceId.includes('000000000000000000000')) {
    console.warn(`Stripe Price ID for ${key} is not properly configured.`);
  }
  return priceId;
}

/**
 * Homepage pricing tiers - derived from subscription plans
 * Used by Pricing.tsx on homepage
 * Now unified with subscription.config.ts
 */
export const HOMEPAGE_TIERS = buildHomepageTiers() as const;

// =============================================================================
// Stripe Configuration Validation & Access
// =============================================================================

/**
 * Get the Stripe publishable key for client-side usage
 */
export function getStripePublishableKey(): string {
  return clientEnv.STRIPE_PUBLISHABLE_KEY;
}

/**
 * Get the Stripe secret key for server-side usage
 * Only accessible on the server
 */
export function getStripeSecretKey(): string {
  return serverEnv.STRIPE_SECRET_KEY || '';
}

/**
 * Get the Stripe webhook secret for server-side webhook verification
 */
export function getStripeWebhookSecret(): string {
  return serverEnv.STRIPE_WEBHOOK_SECRET || '';
}

/**
 * Complete Stripe configuration object
 * Use this to get all Stripe-related configuration in one place
 */
export function getStripeConfig(): {
  publishableKey: string;
  secretKey: string;
  webhookSecret: string;
  prices: typeof STRIPE_PRICES;
  creditPacks: typeof CREDIT_PACKS;
  subscriptionPlans: typeof SUBSCRIPTION_PLANS;
  homepageTiers: typeof HOMEPAGE_TIERS;
} {
  return {
    // Client-side configuration
    publishableKey: clientEnv.STRIPE_PUBLISHABLE_KEY,

    // Server-side configuration (only available on server)
    secretKey: serverEnv.STRIPE_SECRET_KEY || '',
    webhookSecret: serverEnv.STRIPE_WEBHOOK_SECRET || '',

    // Price IDs
    prices: STRIPE_PRICES,

    // Product configurations
    creditPacks: CREDIT_PACKS,
    subscriptionPlans: SUBSCRIPTION_PLANS,

    // Homepage pricing
    homepageTiers: HOMEPAGE_TIERS,
  };
}

/**
 * Validate that all required Stripe configuration is present
 * Returns an object with validation results
 */
export function validateStripeConfig(): {
  isValid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Check client-side configuration
  if (!clientEnv.STRIPE_PUBLISHABLE_KEY) {
    errors.push('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is not configured');
  } else if (clientEnv.STRIPE_PUBLISHABLE_KEY.includes('pk_test_xxx') || clientEnv.STRIPE_PUBLISHABLE_KEY.includes('pk_live_xxx')) {
    warnings.push('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY appears to be a placeholder key');
  }

  // Check server-side configuration
  if (!serverEnv.STRIPE_SECRET_KEY) {
    errors.push('STRIPE_SECRET_KEY is not configured');
  } else if (serverEnv.STRIPE_SECRET_KEY.includes('dummy') || serverEnv.STRIPE_SECRET_KEY.includes('placeholder')) {
    warnings.push('STRIPE_SECRET_KEY appears to be a dummy/placeholder key');
  }

  if (!serverEnv.STRIPE_WEBHOOK_SECRET) {
    warnings.push('STRIPE_WEBHOOK_SECRET is not configured - webhook signature verification will fail');
  }

  // Check price IDs
  const missingPrices = Object.entries(STRIPE_PRICES)
    .filter(([, priceId]) => !priceId || priceId.includes('000000000000000000000'))
    .map(([key]) => key);

  if (missingPrices.length > 0) {
    errors.push(`Missing or invalid Stripe Price IDs: ${missingPrices.join(', ')}`);
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
}

/**
 * Get subscription plan details for a given price ID
 * Now uses unified resolver from subscription.config.ts
 */
export function getPlanForPriceId(priceId: string): (typeof SUBSCRIPTION_PLANS)[keyof typeof SUBSCRIPTION_PLANS] | null {
  const resolved = resolvePriceId(priceId);

  // Only return plans, not credit packs
  if (!resolved || resolved.type !== 'plan') {
    return null;
  }

  // Convert unified format to legacy format
  const planKey = `${resolved.key.toUpperCase()}_${resolved.currency === 'usd' ? 'MONTHLY' : 'YEARLY'}` as keyof typeof SUBSCRIPTION_PLANS;
  return SUBSCRIPTION_PLANS[planKey] || null;
}

/**
 * Get display name for a subscription plan tier
 * Accepts either a string tier name or an object with priceId and subscriptionTier
 */
export function getPlanDisplayName(input: string | { priceId: string; subscriptionTier?: string | null }): string {
  if (typeof input === 'string') {
    // Handle string input (legacy support)
    switch (input.toLowerCase()) {
      case 'hobby':
      case 'HOBBY_MONTHLY':
        return SUBSCRIPTION_PLANS.HOBBY_MONTHLY.name;
      case 'pro':
      case 'professional':
      case 'PRO_MONTHLY':
        return SUBSCRIPTION_PLANS.PRO_MONTHLY.name;
      case 'business':
      case 'BUSINESS_MONTHLY':
        return SUBSCRIPTION_PLANS.BUSINESS_MONTHLY.name;
      default:
        return input;
    }
  }

  // Handle object input with priceId and subscriptionTier
  const { priceId, subscriptionTier } = input;

  // First try to get plan by priceId
  const plan = getPlanForPriceId(priceId);
  if (plan) {
    return plan.name;
  }

  // Fallback to subscriptionTier
  if (subscriptionTier) {
    return getPlanDisplayName(subscriptionTier);
  }

  // Final fallback
  return 'Unknown Plan';
}

// =============================================================================
// Unified Resolver Exports
// =============================================================================

/**
 * Export unified resolver functions for easy import by other modules
 * These provide the single source of truth for price lookups
 */
export {
  getPriceIndex,
  resolvePriceId,
  resolvePlanOrPack,
  assertKnownPriceId,
};

/**
 * Check if Stripe is properly configured for payments
 * This is a convenience function that returns true if the essential configuration is present
 */
export function isStripeConfigured(): boolean {
  const validation = validateStripeConfig();
  return validation.isValid && serverEnv.STRIPE_SECRET_KEY.length > 0;
}
