import { execFileSync, spawnSync } from 'node:child_process';
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { env as runtimeEnv } from 'node:process';
import { afterEach, describe, expect, it } from 'vitest';
import { parse } from 'yaml';
import { readExecutorRuntimeConfig } from '../../../services/upscale-executor/index';

const source = path.resolve('services/upscale-executor');
const fixtures: string[] = [];
const digest = `sha256:${'a'.repeat(64)}`;
const account = (name: string) => `${name}@miu-test.iam.gserviceaccount.com`;
const executorUrl = 'https://upscale-executor-123456789012.us-central1.run.app';
const dispatcherUrl = 'https://upscale-executor-dispatcher-123456789012.us-central1.run.app';
const callbackUrl = 'https://upscale-executor-callbacks-123456789012.us-central1.run.app';

// The fixture intercepts every gcloud command. Unknown commands fail closed;
// mutations change local JSON only, never Google Cloud resources.
const stub = `#!/usr/bin/env node
const fs = require('node:fs');
const args = process.argv.slice(2), dir = process.env.MOCK_DIR;
fs.appendFileSync(dir + '/calls.jsonl', JSON.stringify(args) + '\\n');
const file = dir + '/state.json';
const state = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file)) : { services: {}, policies: {}, queue: null, scheduler: null };
const command = args.filter(a => !a.startsWith('--'));
const is = prefix => command.slice(0, prefix.split(' ').length).join(' ') === prefix;
const flag = name => args.find(a => a.startsWith('--' + name + '='))?.slice(name.length + 3);
const pairs = name => Object.fromEntries((flag(name) || '').split(',').filter(Boolean).map(p => [p.slice(0,p.indexOf('=')), p.slice(p.indexOf('=')+1)]));
const save = () => fs.writeFileSync(file, JSON.stringify(state));
const out = value => console.log(typeof value === 'string' ? value : JSON.stringify(value));
if (is('projects describe')) out('123456789012');
else if (is('services list')) out(['run','cloudtasks','cloudscheduler','artifactregistry','cloudbuild','secretmanager'].map(s => s + '.googleapis.com').join('\\n'));
else if (is('iam service-accounts describe') || is('artifacts repositories describe')) out(command[3] || 'present');
else if (is('secrets versions describe')) out('ENABLED');
else if (is('builds submit')) {
  // The real CLI creates this when it is absent. A release must not dirty its source checkout.
  if (fs.existsSync(command[2] + '/ignored-secret.txt')) process.exit(91);
  fs.writeFileSync(command[2] + '/.gcloudignore', '# Generated by gcloud');
  state.build = args; save();
}
else if (is('artifacts docker images describe')) out('sha256:' + 'a'.repeat(64));
else if (is('run deploy')) {
  const name = command[2]; state.services[name] = { args, env: pairs('set-env-vars'), secrets: pairs('set-secrets') };
  state.policies[name] ||= [];
  if (args.includes('--allow-unauthenticated')) state.policies[name].push({role:'roles/run.invoker',members:['allUsers']});
  save();
} else if (is('run services add-iam-policy-binding')) {
  (state.policies[command[3]] ||= []).push({ role: flag('role'), members: [flag('member')] }); save();
} else if (is('run services get-iam-policy')) {
  const bindings = [...(state.policies[command[3]] || [])];
  if (process.env.MOCK_BAD_IAM === '1') bindings.push({role:'roles/run.invoker',members:['allUsers']});
  out({bindings});
} else if (is('run services update-traffic')) { /* all fixture deployments use 100% traffic */ }
else if (is('run services describe')) {
  const name = command[3]; if (!state.services[name]) process.exit(1);
  const audience = state.services[name].args.find(a => a.startsWith('--add-custom-audiences='))?.split('=')[1];
  out({ metadata: {annotations:{'run.googleapis.com/custom-audiences':JSON.stringify([process.env.MOCK_BAD_AUDIENCE === '1' ? 'https://wrong.test' : audience])}}, status: {latestReadyRevisionName:name+'-00001', latestCreatedRevisionName:name+'-00001', url:'https://'+name+'-123456789012.us-central1.run.app', traffic:[{revisionName:name+'-00001',percent:100}]} });
} else if (is('run revisions describe')) {
  const name = command[3].replace(/-00001$/, ''), service = state.services[name];
  if (process.env.MOCK_BAD_ENV === '1') service.env.UPSCALE_EXECUTOR_HEALTH_SERVICE_ACCOUNT = 'wrong@miu-test.iam.gserviceaccount.com';
  const value = key => service.args.find(a => a.startsWith('--'+key+'='))?.slice(key.length+3);
  out({ metadata: {annotations:{'autoscaling.knative.dev/maxScale':value('max-instances')}}, spec: {
    serviceAccountName:value('service-account'),containerConcurrency:Number(value('concurrency')),timeoutSeconds:Number(value('timeout').replace('s','')),
    containers:[{image:process.env.MOCK_BAD_IMAGE === '1' ? 'wrong:latest' : value('image'),resources:{limits:{cpu:value('cpu'),memory:value('memory')}},env:[
      ...Object.entries(service.env).map(([name,value])=>({name,value})),
      ...Object.entries(service.secrets).map(([name,ref])=>({name,valueFrom:{secretKeyRef:{name:ref.split(':')[0],key:ref.split(':')[1]}}}))
    ]}]
  }});
} else if (is('tasks queues list')) out(state.queue ? [state.queue] : []);
else if (is('tasks queues create') || is('tasks queues update')) {
  state.queue = {name:'projects/miu-test/locations/us-central1/queues/'+command[3],state:'RUNNING',rateLimits:{maxConcurrentDispatches:Number(flag('max-concurrent-dispatches')),maxDispatchesPerSecond:Number(flag('max-dispatches-per-second'))}}; save();
} else if (is('tasks queues describe')) out(state.queue);
else if (is('scheduler jobs list')) out(state.scheduler ? [state.scheduler] : []);
else if (is('scheduler jobs create http') || is('scheduler jobs update http')) {
  state.scheduler = {name:command[4],schedule:flag('schedule'),state:'ENABLED',httpTarget:{uri:flag('uri'),httpMethod:flag('http-method'),oidcToken:{serviceAccountEmail:flag('oidc-service-account-email'),audience:flag('oidc-token-audience')}}}; save();
} else if (is('scheduler jobs describe')) out(state.scheduler);
else if (is('secrets add-iam-policy-binding') || is('iam service-accounts add-iam-policy-binding') || is('tasks queues add-iam-policy-binding') || is('projects add-iam-policy-binding')) { /* recorded above */ }
else { console.error('Unsupported stub command: ' + args.join(' ')); process.exit(90); }
`;

function fixture() {
  const dir = mkdtempSync(path.join(tmpdir(), 'upscale-deploy-'));
  fixtures.push(dir);
  const repo = path.join(dir, 'repo');
  const scripts = path.join(repo, 'services/upscale-executor');
  mkdirSync(scripts, { recursive: true });
  for (const file of ['deploy.sh', 'cloudbuild.yaml'])
    cpSync(path.join(source, file), path.join(scripts, file));
  writeFileSync(path.join(repo, '.gitignore'), 'ignored-secret.txt\n');
  execFileSync('git', ['init', '--quiet', repo]);
  execFileSync('git', ['-C', repo, 'add', '.']);
  execFileSync('git', [
    '-C',
    repo,
    '-c',
    'user.name=Fixture',
    '-c',
    'user.email=fixture@example.test',
    'commit',
    '--quiet',
    '-m',
    'fixture',
  ]);
  const sha = execFileSync('git', ['-C', repo, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
  writeFileSync(path.join(repo, 'ignored-secret.txt'), 'fixture-only-upload-canary');
  const bin = path.join(dir, 'bin');
  mkdirSync(bin);
  writeFileSync(path.join(bin, 'gcloud'), stub, { mode: 0o700 });
  const env = {
    ...runtimeEnv,
    PATH: `${bin}:${runtimeEnv.PATH}`,
    MOCK_DIR: dir,
    GCP_PROJECT_ID: 'miu-test',
    GCP_REGION: 'us-central1',
    ARTIFACT_REGISTRY_REPOSITORY: 'executors',
    CLOUD_RUN_SERVICE_ACCOUNT: account('executor'),
    DISPATCH_SERVICE_ACCOUNT: account('dispatcher'),
    CALLBACK_SERVICE_ACCOUNT: account('callbacks'),
    TASK_SERVICE_ACCOUNT: account('tasks'),
    SCHEDULER_SERVICE_ACCOUNT: account('scheduler'),
    SUPABASE_URL_SECRET_REF: 'supabase-url:4',
    SUPABASE_SERVICE_ROLE_KEY_SECRET_REF: 'supabase-key:5',
    REPLICATE_API_TOKEN_SECRET_REF: 'replicate-token:6',
    GEMINI_API_KEY_SECRET_REF: 'gemini-key:7',
    OPENROUTER_API_KEY_SECRET_REF: 'openrouter-key:8',
    REPLICATE_WEBHOOK_SECRET_REF: 'replicate-webhook:9',
    WAKE_SECRET_REF: 'upscale-wake:10',
    BUILD_ID: sha,
  };
  return {
    repo,
    sha,
    run: (overrides: Record<string, string> = {}) =>
      spawnSync('bash', [path.join(scripts, 'deploy.sh')], {
        env: { ...env, ...overrides },
        encoding: 'utf8',
        timeout: 25000,
      }),
    calls: () => {
      try {
        return readFileSync(path.join(dir, 'calls.jsonl'), 'utf8')
          .trim()
          .split('\n')
          .filter(Boolean)
          .map(line => JSON.parse(line) as string[]);
      } catch {
        return [];
      }
    },
  };
}

const starts = (args: string[], prefix: string) =>
  args.slice(0, prefix.split(' ').length).join(' ') === prefix;
const option = (args: string[], name: string) =>
  args.find(value => value.startsWith(`--${name}=`))?.slice(name.length + 3);
const values = (args: string[], name: string) =>
  Object.fromEntries(
    (option(args, name) ?? '')
      .split(',')
      .filter(Boolean)
      .map(value => [value.slice(0, value.indexOf('=')), value.slice(value.indexOf('=') + 1)])
  );
afterEach(() => {
  for (const dir of fixtures.splice(0)) rmSync(dir, { recursive: true, force: true });
});

describe('upscale executor deployment commands', () => {
  it('builds the source SHA and wires three isolated roles, pinned secrets, IAM, tasks and Scheduler', () => {
    const test = fixture();
    const result = test.run();
    expect(result.status, result.stderr).toBe(0);
    const calls = test.calls();
    const build = calls.find(call => starts(call, 'builds submit'))!;
    expect(build[2]).not.toBe(test.repo);
    expect(option(build, 'config')).toBe(
      path.join(build[2], 'services/upscale-executor/cloudbuild.yaml')
    );
    expect(option(build, 'substitutions')).toContain(`_SOURCE_SHA=${test.sha}`);
    const config = parse(readFileSync(path.join(source, 'cloudbuild.yaml'), 'utf8'));
    const buildArgs = config.steps[0].args.map((arg: string) =>
      arg.replace('${_SOURCE_SHA}', test.sha)
    );
    expect(buildArgs).toContain(`--build-arg=UPSCALE_BUILD_ID=${test.sha}`);
    expect(buildArgs.at(-1)).toBe('.');
    const deploys = calls.filter(call => starts(call, 'run deploy'));
    expect(deploys).toHaveLength(3);
    const role = (mode: string) =>
      deploys.find(call => values(call, 'set-env-vars').UPSCALE_EXECUTOR_MODE === mode)!;
    for (const deploy of deploys) {
      const runtime = readExecutorRuntimeConfig(values(deploy, 'set-env-vars'));
      expect(runtime).toMatchObject({
        mode: values(deploy, 'set-env-vars').UPSCALE_EXECUTOR_MODE,
        taskAudience: executorUrl,
        taskTargetUrl: executorUrl,
        taskServiceAccount: account('tasks'),
        healthServiceAccount: account('dispatcher'),
        dispatchAudience: dispatcherUrl,
        dispatchServiceAccount: account('scheduler'),
        callbackBaseUrl: `${callbackUrl}/webhooks/replicate`,
        imageDigest: digest,
        buildId: test.sha,
        port: 8080,
      });
      expect(option(deploy, 'image')).toBe(
        `us-central1-docker.pkg.dev/miu-test/executors/upscale-executor@${digest}`
      );
      expect(values(deploy, 'set-env-vars')).toMatchObject({
        UPSCALE_BUILD_ID: test.sha,
        UPSCALE_EXECUTOR_IMAGE_DIGEST: digest,
        UPSCALE_EXECUTOR_TASK_TARGET_URL: executorUrl,
        UPSCALE_EXECUTOR_TASK_AUDIENCE: executorUrl,
        UPSCALE_EXECUTOR_HEALTH_SERVICE_ACCOUNT: account('dispatcher'),
        UPSCALE_EXECUTOR_CALLBACK_BASE_URL: `${callbackUrl}/webhooks/replicate`,
      });
      expect(deploy).toContain('--invoker-iam-check');
      expect(values(deploy, 'set-secrets').SUPABASE_SERVICE_ROLE_KEY).toBe('supabase-key:5');
    }
    expect(role('executor')).toEqual(
      expect.arrayContaining([
        '--no-allow-unauthenticated',
        '--memory=1Gi',
        '--cpu=1',
        '--concurrency=1',
        '--max-instances=10',
        '--timeout=900s',
      ])
    );
    expect(role('dispatcher')).toEqual(
      expect.arrayContaining([
        '--no-allow-unauthenticated',
        '--min-instances=1',
        '--no-cpu-throttling',
      ])
    );
    expect(role('callbacks')).toContain('--allow-unauthenticated');
    expect(values(role('executor'), 'set-secrets')).toMatchObject({
      GEMINI_API_KEY: 'gemini-key:7',
      OPENROUTER_API_KEY: 'openrouter-key:8',
    });
    expect(values(role('callbacks'), 'set-secrets')).toMatchObject({
      REPLICATE_WEBHOOK_SIGNING_SECRET: 'replicate-webhook:9',
      UPSCALE_EXECUTOR_WAKE_SECRET: 'upscale-wake:10',
    });
    const queue = calls.find(call => starts(call, 'tasks queues create'))!;
    expect(queue).toContain('--max-concurrent-dispatches=10');
    const scheduler = calls.find(call => starts(call, 'scheduler jobs create http'))!;
    expect(scheduler).toEqual(
      expect.arrayContaining([
        `--uri=${dispatcherUrl}/dispatch`,
        `--oidc-token-audience=${dispatcherUrl}`,
        `--oidc-service-account-email=${account('scheduler')}`,
        '--schedule=* * * * *',
      ])
    );
    for (const [service, identity] of [
      ['upscale-executor', 'tasks'],
      ['upscale-executor', 'dispatcher'],
      ['upscale-executor-dispatcher', 'scheduler'],
    ]) {
      expect(calls).toContainEqual(
        expect.arrayContaining([
          'run',
          'services',
          'add-iam-policy-binding',
          service,
          `--member=serviceAccount:${account(identity)}`,
          '--role=roles/run.invoker',
        ])
      );
    }
    for (const identity of ['dispatcher', 'callbacks']) {
      expect(calls).toContainEqual(
        expect.arrayContaining([
          'tasks',
          'queues',
          'add-iam-policy-binding',
          `--member=serviceAccount:${account(identity)}`,
          '--role=roles/cloudtasks.enqueuer',
        ])
      );
      expect(calls).toContainEqual(
        expect.arrayContaining([
          'iam',
          'service-accounts',
          'add-iam-policy-binding',
          account('tasks'),
          `--member=serviceAccount:${account(identity)}`,
          '--role=roles/iam.serviceAccountUser',
        ])
      );
    }
    expect(calls.some(call => starts(call, 'secrets versions access'))).toBe(false);
    expect(test.run().status).toBe(0);
    expect(test.calls().some(call => starts(call, 'tasks queues update'))).toBe(true);
    expect(test.calls().some(call => starts(call, 'scheduler jobs update http'))).toBe(true);
  }, 30000);

  it.each([
    ['unpinned secret', { WAKE_SECRET_REF: 'upscale-wake:latest' }],
    ['mismatched source', { BUILD_ID: 'b'.repeat(40) }],
    ['foreign identity', { TASK_SERVICE_ACCOUNT: 'tasks@another-project.iam.gserviceaccount.com' }],
  ])('rejects %s before any cloud mutation', (_name, overrides) => {
    const test = fixture();
    expect(test.run(overrides).status).not.toBe(0);
    expect(
      test
        .calls()
        .some(call => /submit|deploy|create|update|add-iam-policy-binding/.test(call.join(' ')))
    ).toBe(false);
  });

  it('refuses dirty source before any cloud command', () => {
    const test = fixture();
    writeFileSync(path.join(test.repo, 'uncommitted.txt'), 'dirty');
    expect(test.run().status).not.toBe(0);
    expect(test.calls()).toHaveLength(0);
  });

  it.each(['MOCK_BAD_IMAGE', 'MOCK_BAD_IAM', 'MOCK_BAD_AUDIENCE', 'MOCK_BAD_ENV'])(
    'fails release verification for %s',
    failure => {
      const test = fixture();
      const result = test.run({ [failure]: '1' });
      expect(result.status).not.toBe(0);
      expect(result.stderr).not.toContain('Verified all three');
    },
    30000
  );
});
