#!/bin/bash

# Generic Environment Loader Script
# Loads environment variables from .env.client and .env.api files
# Use --prod flag to load production files (.env.client.prod, .env.api.prod)

set -euo pipefail

# Determine environment based on flag
ENV_SUFFIX=""
if [[ "${1:-}" == "--prod" ]]; then
    ENV_SUFFIX=".prod"
    shift
fi

ENV_CLIENT=".env.client${ENV_SUFFIX}"
ENV_API=".env.api${ENV_SUFFIX}"

# Function to load a single env file
load_env_file() {
    local file=$1

    if [ -f "$file" ]; then
        echo "✅ Loading environment variables from $file"

        # Export all non-comment lines
        while IFS= read -r line; do
            # Skip comments and empty lines
            [[ $line =~ ^[[:space:]]*# ]] && continue
            [[ $line =~ ^[[:space:]]*$ ]] && continue

            # Export valid KEY=VALUE pairs (support both NEXT_PUBLIC_ and non-prefixed)
            if [[ $line =~ ^[A-Z_][A-Z0-9_]*= ]]; then
                export "$line"
            fi
        done < "$file"

        return 0
    else
        return 1
    fi
}

# Load .env.client (public vars)
if ! load_env_file "$ENV_CLIENT"; then
    echo "❌ Environment file '$ENV_CLIENT' not found!"
    if [[ -n "$ENV_SUFFIX" ]]; then
        echo "💡 Production env files are generated by the deploy script from GCloud Secret Manager"
    else
        echo "💡 Copy .env.client.example to .env.client and fill in your values"
    fi
    exit 1
fi

# Load .env.api (server secrets)
if ! load_env_file "$ENV_API"; then
    echo "❌ Environment file '$ENV_API' not found!"
    if [[ -n "$ENV_SUFFIX" ]]; then
        echo "💡 Production env files are generated by the deploy script from GCloud Secret Manager"
    else
        echo "💡 Copy .env.api.example to .env.api and fill in your values"
    fi
    exit 1
fi

echo "✅ All environment variables loaded successfully"

# Keep public Stripe price IDs aligned with the active Stripe account.
# If the client env file omits them, inherit from the server-side Stripe price IDs
# so Next.js and the checkout API target the same Stripe account.
sync_public_stripe_prices() {
    local mappings=(
        "NEXT_PUBLIC_STRIPE_PRICE_STARTER:STRIPE_PRICE_STARTER"
        "NEXT_PUBLIC_STRIPE_PRICE_HOBBY:STRIPE_PRICE_HOBBY"
        "NEXT_PUBLIC_STRIPE_PRICE_PRO:STRIPE_PRICE_PRO"
        "NEXT_PUBLIC_STRIPE_PRICE_BUSINESS:STRIPE_PRICE_BUSINESS"
        "NEXT_PUBLIC_STRIPE_PRICE_CREDITS_SMALL:STRIPE_PRICE_CREDITS_SMALL"
        "NEXT_PUBLIC_STRIPE_PRICE_CREDITS_MEDIUM:STRIPE_PRICE_CREDITS_MEDIUM"
        "NEXT_PUBLIC_STRIPE_PRICE_CREDITS_LARGE:STRIPE_PRICE_CREDITS_LARGE"
    )

    for mapping in "${mappings[@]}"; do
        local public_var="${mapping%%:*}"
        local server_var="${mapping##*:}"
        local current_public="${!public_var:-}"
        local current_server="${!server_var:-}"

        if [[ -z "$current_public" && -n "$current_server" ]]; then
            export "$public_var=$current_server"
        fi
    done
}

sync_public_stripe_prices

# Function to validate required variables
validate_required_vars() {
    local missing_vars=()

    for var in "$@"; do
        if [ -z "${!var:-}" ]; then
            missing_vars+=("$var")
        fi
    done

    if [ ${#missing_vars[@]} -gt 0 ]; then
        echo "❌ Missing required environment variables:"
        printf '   %s\n' "${missing_vars[@]}"
        exit 1
    fi
}

# Function to print loaded vars (with masking for sensitive ones)
print_loaded_vars() {
    local sensitive_patterns=("SECRET" "KEY" "TOKEN" "PASSWORD")

    for env_file in "$ENV_CLIENT" "$ENV_API"; do
        if [ -f "$env_file" ]; then
            echo ""
            echo "📋 Variables from $env_file:"

            while IFS= read -r line; do
                # Skip comments and empty lines
                [[ $line =~ ^[[:space:]]*# ]] && continue
                [[ $line =~ ^[[:space:]]*$ ]] && continue

                # Extract key and value
                if [[ $line =~ ^([A-Z_][A-Z0-9_]*)=(.*)$ ]]; then
                    key="${BASH_REMATCH[1]}"
                    value="${BASH_REMATCH[2]}"

                    # Check if this is a sensitive variable
                    is_sensitive=false
                    for pattern in "${sensitive_patterns[@]}"; do
                        if [[ $key == *"$pattern"* ]]; then
                            is_sensitive=true
                            break
                        fi
                    done

                    if [ "$is_sensitive" = true ]; then
                        # Show first 10 chars + masked
                        masked_value="${value:0:10}...***"
                        echo "   $key=$masked_value"
                    else
                        echo "   $key=$value"
                    fi
                fi
            done < "$env_file"
        fi
    done
}

# If script is called with --validate flag, validate common required vars
if [ "${1:-}" = "--validate" ]; then
    shift
    validate_required_vars "$@"
fi

# If script is called with --print flag, print loaded vars
if [ "${1:-}" = "--print" ]; then
    print_loaded_vars
fi
