-- Shared provider health events and circuit state for all Cloudflare isolates.
CREATE TABLE IF NOT EXISTS public.provider_health_state (
    provider TEXT PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'closed'
        CHECK (status IN ('closed', 'open', 'half_open')),
    consecutive_failures INTEGER NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0),
    opened_until TIMESTAMP WITH TIME ZONE,
    last_failure_at TIMESTAMP WITH TIME ZONE,
    last_success_at TIMESTAMP WITH TIME ZONE,
    last_alerted_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.provider_health_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    success BOOLEAN NOT NULL,
    failure_kind TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_provider_health_events_provider_created
    ON public.provider_health_events(provider, created_at DESC);

ALTER TABLE public.provider_health_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_health_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access to provider health state"
    ON public.provider_health_state FOR ALL TO service_role
    USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access to provider health events"
    ON public.provider_health_events FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.get_provider_circuit_availability(p_provider TEXT)
RETURNS TABLE(
    available BOOLEAN,
    circuit_status TEXT,
    retry_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
    SELECT
        CASE
            WHEN state.status = 'half_open' THEN FALSE
            WHEN state.status = 'open' AND state.opened_until > NOW() THEN FALSE
            ELSE TRUE
        END,
        CASE
            WHEN state.status = 'open' AND state.opened_until <= NOW() THEN 'half_open'
            ELSE state.status
        END,
        CASE
            WHEN state.status = 'open' AND state.opened_until > NOW() THEN state.opened_until
            ELSE NULL
        END
    FROM public.provider_health_state AS state
    WHERE state.provider = p_provider
    UNION ALL
    SELECT TRUE, 'closed', NULL::TIMESTAMP WITH TIME ZONE
    WHERE NOT EXISTS (
        SELECT 1 FROM public.provider_health_state WHERE provider = p_provider
    )
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.acquire_provider_circuit_permit(p_provider TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_state public.provider_health_state%ROWTYPE;
BEGIN
    INSERT INTO public.provider_health_state(provider)
    VALUES (p_provider)
    ON CONFLICT (provider) DO NOTHING;

    SELECT * INTO v_state
    FROM public.provider_health_state
    WHERE provider = p_provider
    FOR UPDATE;

    IF v_state.status = 'half_open' THEN
        RETURN FALSE;
    END IF;

    IF v_state.status = 'open' AND v_state.opened_until > NOW() THEN
        RETURN FALSE;
    END IF;

    IF v_state.status = 'open' THEN
        UPDATE public.provider_health_state
        SET status = 'half_open', updated_at = NOW()
        WHERE provider = p_provider;
    END IF;

    RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_provider_health_outcome(
    p_provider TEXT,
    p_success BOOLEAN,
    p_failure_kind TEXT DEFAULT NULL,
    p_failure_threshold INTEGER DEFAULT 5,
    p_cooldown_seconds INTEGER DEFAULT 300
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_state public.provider_health_state%ROWTYPE;
    v_failure_count INTEGER;
BEGIN
    INSERT INTO public.provider_health_events(provider, success, failure_kind)
    VALUES (p_provider, p_success, CASE WHEN p_success THEN NULL ELSE p_failure_kind END);

    INSERT INTO public.provider_health_state(provider)
    VALUES (p_provider)
    ON CONFLICT (provider) DO NOTHING;

    SELECT * INTO v_state
    FROM public.provider_health_state
    WHERE provider = p_provider
    FOR UPDATE;

    IF p_success THEN
        UPDATE public.provider_health_state
        SET
            status = 'closed',
            consecutive_failures = 0,
            opened_until = NULL,
            last_success_at = NOW(),
            updated_at = NOW()
        WHERE provider = p_provider;
        RETURN;
    END IF;

    v_failure_count := v_state.consecutive_failures + 1;
    UPDATE public.provider_health_state
    SET
        consecutive_failures = v_failure_count,
        status = CASE
            WHEN v_state.status = 'half_open' OR v_failure_count >= p_failure_threshold
                THEN 'open'
            ELSE status
        END,
        opened_until = CASE
            WHEN v_state.status = 'half_open' OR v_failure_count >= p_failure_threshold
                THEN NOW() + make_interval(secs => p_cooldown_seconds)
            ELSE opened_until
        END,
        last_failure_at = NOW(),
        updated_at = NOW()
    WHERE provider = p_provider;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_provider_health_alert(
    p_provider TEXT,
    p_window_minutes INTEGER DEFAULT 10,
    p_min_attempts INTEGER DEFAULT 5,
    p_failure_ratio NUMERIC DEFAULT 0.5,
    p_alert_cooldown_minutes INTEGER DEFAULT 30
)
RETURNS TABLE(
    should_alert BOOLEAN,
    attempts BIGINT,
    failures BIGINT,
    failure_ratio NUMERIC,
    billing_failures BIGINT,
    circuit_status TEXT,
    retry_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_state public.provider_health_state%ROWTYPE;
    v_attempts BIGINT;
    v_failures BIGINT;
    v_billing_failures BIGINT;
    v_ratio NUMERIC;
    v_should_alert BOOLEAN;
BEGIN
    INSERT INTO public.provider_health_state(provider)
    VALUES (p_provider)
    ON CONFLICT (provider) DO NOTHING;

    SELECT
        COUNT(*),
        COUNT(*) FILTER (WHERE success = FALSE),
        COUNT(*) FILTER (WHERE success = FALSE AND failure_kind = 'billing')
    INTO v_attempts, v_failures, v_billing_failures
    FROM public.provider_health_events
    WHERE provider = p_provider
      AND created_at >= NOW() - make_interval(mins => p_window_minutes);

    v_ratio := CASE
        WHEN v_attempts = 0 THEN 0
        ELSE v_failures::NUMERIC / v_attempts::NUMERIC
    END;

    SELECT * INTO v_state
    FROM public.provider_health_state
    WHERE provider = p_provider
    FOR UPDATE;

    v_should_alert :=
        v_attempts >= p_min_attempts
        AND v_ratio >= p_failure_ratio
        AND (
            v_state.last_alerted_at IS NULL
            OR v_state.last_alerted_at
                < NOW() - make_interval(mins => p_alert_cooldown_minutes)
        );

    IF v_should_alert THEN
        UPDATE public.provider_health_state
        SET last_alerted_at = NOW(), updated_at = NOW()
        WHERE provider = p_provider;
    END IF;

    DELETE FROM public.provider_health_events
    WHERE created_at < NOW() - INTERVAL '24 hours';

    RETURN QUERY SELECT
        v_should_alert,
        v_attempts,
        v_failures,
        v_ratio,
        v_billing_failures,
        v_state.status,
        v_state.opened_until;
END;
$$;

CREATE OR REPLACE FUNCTION public.release_provider_health_alert_claim(p_provider TEXT)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    UPDATE public.provider_health_state
    SET last_alerted_at = NULL, updated_at = NOW()
    WHERE provider = p_provider
      AND last_alerted_at >= NOW() - INTERVAL '5 minutes';
$$;

REVOKE ALL ON FUNCTION public.get_provider_circuit_availability(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.acquire_provider_circuit_permit(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_provider_health_outcome(TEXT, BOOLEAN, TEXT, INTEGER, INTEGER)
    FROM PUBLIC;
REVOKE ALL ON FUNCTION public.claim_provider_health_alert(TEXT, INTEGER, INTEGER, NUMERIC, INTEGER)
    FROM PUBLIC;
REVOKE ALL ON FUNCTION public.release_provider_health_alert_claim(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_provider_circuit_availability(TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.acquire_provider_circuit_permit(TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.record_provider_health_outcome(TEXT, BOOLEAN, TEXT, INTEGER, INTEGER)
    TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_provider_health_alert(TEXT, INTEGER, INTEGER, NUMERIC, INTEGER)
    TO service_role;
GRANT EXECUTE ON FUNCTION public.release_provider_health_alert_claim(TEXT) TO service_role;
